name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - development  # Use 'development' para acionar o deploy com base nesta branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔥 Remove .git and .github directories
        run: |
          rm -rf .git
          rm -rf .github

      - name: 🔄 Update file paths and URLs
        run: |
          find . -type f -name "*.php" -exec sed -i 's|Wamp64Connection\.php|DBConnection.php|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://localhost/LonyExtra/|https://lonyextra.com/|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://127.0.0.1:5500/|https://lonyextra.com/|g' {} +

      - name: 🔄 Update userId in JavaScript files
        run: |
            find . -type f -name "*.js" -exec sed -i 's|const userId = "391f58325968d93b6778b9722f953bb063b44254d8e04109955c52b928ac9782";|const userId = localStorage.getItem("userId");|g' {} +

      - name: 🔧 Remove debugging and CORS headers from PHP files
        run: |
          find . -type f -name "*.php" -exec sed -i "/error_reporting(E_ALL);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/ini_set('display_errors', 1);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Origin: \*');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Methods: POST, OPTIONS');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Headers: Content-Type');/d" {} +

      - name: 🔨 Remove specific HTML comment around Sentry script
        run: |
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|<!-- <script src="https://js.sentry-cdn.com/a41ea66a6911b5025e8922b0df576302.min.js" crossorigin="anonymous"></script> -->|<script src="https://js.sentry-cdn.com/a41ea66a6911b5025e8922b0df576302.min.js" crossorigin="anonymous"></script>|g' {} +

      - name: 🔧 Remove specific comment from JavaScript files
        run: |
            find . -type f -name "*.js" -exec sed -i 's|//window.location.href = ../../0/access/login.html; ##REMOVE IN yml|window.location.href = ../../0/access/login.html;|g' {} +

      - name: 📂 Setup SSH for Deployment
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_VPS" > ~/.ssh/id_rsa  # Usando a chave SSH configurada como segredo
          chmod 600 ~/.ssh/id_rsa
          # Opcional: Use ssh-keyscan se necessário
          ssh-keyscan -H 123.45.67.89 >> ~/.ssh/known_hosts

      - name: 📂 Deploy to VPS
        run: |
          # Usar o rsync para sincronizar os arquivos, com a chave SSH configurada
          rsync -avz --exclude='.git' --exclude='.github' --exclude='node_modules' -e "ssh -o StrictHostKeyChecking=no" ./ nelioalbasine@191.101.18.114:/var/www/html/
