on:
  push:
    branches:
      - production

name: 🚀 Deploy website on production

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔄 Update file paths and URLs
        run: |
          # Atualizar o nome do arquivo de conexão do banco de dados
          find . -type f -name "*.php" -exec sed -i 's|Wamp64Connection\.php|DBConnection.php|g' {} +

          # Atualizar URLs
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://localhost/LonyExtra/|https://lonyextra.com/|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://127.0.0.1:5500/|https://lonyextra.com/|g' {} +

      - name: 🔧 Remove debugging and CORS headers from PHP files
        run: |
          # Remover as linhas de erro e cabeçalhos CORS de arquivos PHP
          find . -type f -name "*.php" -exec sed -i "/error_reporting(E_ALL);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/ini_set('display_errors', 1);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Origin: \*');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Methods: POST, OPTIONS');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Headers: Content-Type');/d" {} +

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_LONY_EXTRA }}
          username: ${{ secrets.FTP_USERNAME_LONY_EXTRA }}
          password: ${{ secrets.FTP_PASSWORD_LONY_EXTRA }}
          server-dir: /
          exclude: |
            !**/php.ini           # Mantém o php.ini no servidor 
            !**/.htaccess         # Mantém o .htaccess no servidor 
            !**/.user.ini         # Mantém o .user.ini no servidor
