on:
  push:
    branches:
      - production

name: 🚀 Deploy website on production

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔄 Update file paths and URLs
        run: |
          # Atualizar caminhos de arquivos e URLs
          find . -type f -name "*.php" -exec sed -i 's|"Wamp64Connection.php"|"DBConnection.php"|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://localhost/LonyExtra/|https://lonyextra.com/|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://127.0.0.1:5500/|https://lonyextra.com/|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://worldtimeapi.org/api/ip|https://worldtimeapi.org/api/ip|g' {} +

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_LONY_EXTRA }}
          username: ${{ secrets.FTP_USERNAME_LONY_EXTRA }}
          password: ${{ secrets.FTP_PASSWORD_LONY_EXTRA }}
          server-dir: /
          exclude: |
            /testscripts/**       # Exclui a pasta testscripts
            /node_modules/**      # Exclui a pasta node_modules
            /.git/**              # Exclui a pasta .git
            /.github/**           # Exclui a pasta .github
            .gitignore            # Exclui o arquivo .gitignore
            composer.*            # Exclui arquivos composer.json e composer.lock
            !.htaccess            # Mantém o .htaccess no servidor
          dangerous-clean-slate: false  # Não apaga arquivos no servidor que não estão no repositório (essa regra torna a de !.htacess rdundante/desnecessarias, mas vamos deixar)
