name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - production

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔥 Remove .git and .github directories
        run: |
          rm -rf .git .github

      - name: 🔄 Update file paths and URLs
        run: |
          find . -type f -name "*.php" -exec sed -i 's|Wamp64Connection\.php|VpsConnection.php|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://localhost/LonyExtra/|http://191.101.18.114/|g' {} +
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|http://127.0.0.1:5500/|http://191.101.18.114/|g' {} +

      - name: 🔄 Update userId in JavaScript files
        run: |
          find . -type f -name "*.js" -exec sed -i 's|const userId = "391f58325968d93b6778b9722f953bb063b44254d8e04109955c52b928ac9782";|const userId = localStorage.getItem("userId");|g' {} +

      - name: 🔧 Remove debugging and CORS headers from PHP files
        run: |
          find . -type f -name "*.php" -exec sed -i "/error_reporting(E_ALL);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/ini_set('display_errors', 1);/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Origin: \*');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Methods: POST, OPTIONS');/d" {} +
          find . -type f -name "*.php" -exec sed -i "/header('Access-Control-Allow-Headers: Content-Type');/d" {} +

      - name: 🔨 Update Sentry script in HTML/JS files
        run: |
          find . \( -name "*.php" -o -name "*.js" -o -name "*.html" \) -exec sed -i 's|<!-- <script src="https://js.sentry-cdn.com/a41ea66a6911b5025e8922b0df576302.min.js" crossorigin="anonymous"></script> -->|<script src="https://js.sentry-cdn.com/a41ea66a6911b5025e8922b0df576302.min.js" crossorigin="anonymous"></script>|g' {} +

      - name: 🔧 Update JavaScript redirection
        run: |
          find . -type f -name "*.js" -exec sed -i 's|//window.location.href = ../../0/access/login.html; ##REMOVE IN yml|window.location.href = ../../0/access/login.html;|g' {} +

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_VPS }}

      - name: 📂 Deploy to VPS
        run: |
          rsync -avz --exclude='.git' --exclude='.github' --exclude='node_modules' -e "ssh -o StrictHostKeyChecking=no" ./ nelioalbasine@191.101.18.114:/var/www/lonyextra/
         
      - name: 📂 Confirm Deployment Success
        run: |
            echo "Deployment to VPS completed successfully!"
  
          